version: '3.3'
services:
  goapi:
    container_name: 'goapi'
    image: 'wliupure/go-web-app'
    ports:
      - '8000:8000'
    depends_on:
      - 'mongo'
  web:
    container_name: 'web'
    image: 'wliupure/node-web-app'
    ports:
      - '8080:8080'
    # volumes:
    #   - './web:/usr/share/nginx/html'
    # depends_on:
    #   - 'api'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'